name: Terraform Apply

on:
  workflow_dispatch:

# Ensure only one workflow per branch runs at a time to prevent concurrent Terraform state changes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # This cancels any in-progress runs of the same group when a new run is triggered
  cancel-in-progress: true

permissions:
  id-token: write # Allows requesting an OIDC token
  contents: read # Required for actions/checkout

env:
  # Default AWS region; update as needed for your deployment
  AWS_REGION: us-east-1
  TerraformStateBucket: yangw067-terrafom-state # Update with your S3 bucket name
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          # Set the AWS region; change if deploying to a different region
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify IAM Role Assumption
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Initialize Terraform
        run:
          terraform init -input=false -backend-config="bucket=${{ env.TerraformStateBucket }}" \
          -backend-config="${{ github.repository_id }}/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Plan
        working-directory: ${{ github.workspace }}
        run: |
          terraform plan -input=false -var-file=terraform.tfvars -out=tf.plan

      - name: Terraform Apply
        run: |
          terraform apply -input=false -auto-approve tf.plan
          echo ${{ github.repository_id }}
          echo ${{ github.ref }}
