name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Allows requesting an OIDC token
  contents: read # Required for actions/checkout

env:
  # Default AWS region; update as needed for your deployment
  AWS_REGION: us-east-1
  TerraformStateBucket: s3://yangw067test/ # Update with your S3 bucket name

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          # Set the AWS region; change if deploying to a different region
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify IAM Role Assumption
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ${{ github.workspace }}
        run: |
          terraform plan -input=false -var-file=terraform.tfvars -out=tf.plan

      - name: Terraform Apply
        run: |
          terraform apply -input=false -auto-approve tf.plan
          echo ${{ github.repository_id }}

      - name: Terraform destroy (optional, uncomment if you want to destroy resources after apply)
        run: terraform destroy -input=false -auto-approve
